name: ddev-tnvgoodsstore
networks:
    ddev_default:
        external: true
        name: ddev_default
    default:
        labels:
            com.ddev.platform: ddev
        name: ddev-tnvgoodsstore_default
services:
    db:
        build:
            args:
                BASE_IMAGE: ddev/ddev-dbserver-mariadb-10.11:v1.23.4
                gid: "1000"
                uid: "1000"
                username: dinht
            context: D:\StudyHK1_2024\mystore\.ddev\.dbimageBuild
            dockerfile: Dockerfile
        cap_add:
            - SYS_NICE
        command: []
        container_name: ddev-TnVGoodsStore-db
        environment:
            COLUMNS: "78"
            DDEV_DATABASE: mariadb:10.11
            DDEV_DATABASE_FAMILY: mysql
            DDEV_HOSTNAME: tnvgoodsstore.ddev.site
            DDEV_PHP_VERSION: "8.3"
            DDEV_PRIMARY_URL: http://tnvgoodsstore.ddev.site
            DDEV_PROJECT: TnVGoodsStore
            DDEV_PROJECT_TYPE: drupal8
            DDEV_ROUTER_HTTP_PORT: "80"
            DDEV_ROUTER_HTTPS_PORT: "443"
            DDEV_SITENAME: TnVGoodsStore
            DDEV_TLD: ddev.site
            DOCKER_IP: 127.0.0.1
            GOARCH: amd64
            GOOS: windows
            HOST_DOCKER_INTERNAL_IP: ""
            IS_DDEV_PROJECT: "true"
            LINES: "25"
            MYSQL_HISTFILE: /mnt/ddev-global-cache/mysqlhistory/TnVGoodsStore-db/mysql_history
            MYSQL_PWD: db
            PGDATABASE: db
            PGHOST: 127.0.0.1
            PGPASSWORD: db
            PGUSER: db
            POSTGRES_DB: db
            POSTGRES_PASSWORD: db
            POSTGRES_USER: db
            TZ: ""
            USER: dinht
        healthcheck:
            interval: 1s
            retries: 70
            start_interval: 1s
            start_period: 4m0s
            timeout: 1m10s
        hostname: TnVGoodsStore-db
        image: ddev/ddev-dbserver-mariadb-10.11:v1.23.4-TnVGoodsStore-built
        labels:
            com.ddev.app-type: drupal8
            com.ddev.approot: D:\StudyHK1_2024\mystore
            com.ddev.platform: ddev
            com.ddev.site-name: TnVGoodsStore
        networks:
            ddev_default: null
            default: null
        ports:
            - host_ip: 127.0.0.1
              mode: ingress
              protocol: tcp
              target: 3306
        restart: "no"
        stop_grace_period: 1m0s
        user: 1000:1000
        volumes:
            - source: database
              target: /var/lib/mysql
              type: volume
              volume:
                nocopy: true
            - bind:
                create_host_path: true
              source: /d/StudyHK1_2024/mystore/.ddev
              target: /mnt/ddev_config
              type: bind
            - bind:
                create_host_path: true
              source: /d/StudyHK1_2024/mystore/.ddev/db_snapshots
              target: /mnt/snapshots
              type: bind
            - source: ddev-global-cache
              target: /mnt/ddev-global-cache
              type: volume
              volume: {}
        working_dir: /home/dinht
    web:
        build:
            args:
                BASE_IMAGE: ./.ddev/.webimageBuild
                DDEV_DATABASE: mariadb:10.11
                DDEV_PHP_VERSION: "8.3"
                gid: "1000"
                uid: "1000"
                username: dinht
            context: D:\StudyHK1_2024\mystore\.ddev\.webimageBuild
            dockerfile: Dockerfile
        cap_add:
            - SYS_PTRACE
        command:
            - /pre-start.sh
        container_name: ddev-TnVGoodsStore-web
        environment:
            COLUMNS: "78"
            COREPACK_ENABLE_DOWNLOAD_PROMPT: "0"
            COREPACK_HOME: /mnt/ddev-global-cache/corepack
            DDEV_COMPOSER_ROOT: /var/www/html
            DDEV_DATABASE: mariadb:10.11
            DDEV_DATABASE_FAMILY: mysql
            DDEV_DOCROOT: web
            DDEV_FILES_DIR: /var/www/html/web/sites/default/files
            DDEV_FILES_DIRS: /var/www/html/web/sites/default/files
            DDEV_HOSTNAME: tnvgoodsstore.ddev.site
            DDEV_MUTAGEN_ENABLED: "true"
            DDEV_PHP_VERSION: "8.3"
            DDEV_PRIMARY_URL: http://tnvgoodsstore.ddev.site
            DDEV_PROJECT: TnVGoodsStore
            DDEV_PROJECT_TYPE: drupal8
            DDEV_ROUTER_HTTP_PORT: "80"
            DDEV_ROUTER_HTTPS_PORT: "443"
            DDEV_SITENAME: TnVGoodsStore
            DDEV_TLD: ddev.site
            DDEV_VERSION: v1.23.4
            DDEV_WEB_ENTRYPOINT: /mnt/ddev_config/web-entrypoint.d
            DDEV_WEBSERVER_TYPE: nginx-fpm
            DDEV_XDEBUG_ENABLED: "false"
            DEPLOY_NAME: local
            DOCKER_IP: 127.0.0.1
            DOCROOT: web
            DRUSH_ALLOW_XDEBUG: "1"
            DRUSH_OPTIONS_URI: http://tnvgoodsstore.ddev.site
            GOARCH: amd64
            GOOS: windows
            HOST_DOCKER_INTERNAL_IP: ""
            HTTP_EXPOSE: 80:80,8025:8025
            HTTPS_EXPOSE: 443:80,8026:8025
            IS_DDEV_PROJECT: "true"
            LINES: "25"
            MYSQL_HISTFILE: /mnt/ddev-global-cache/mysqlhistory/TnVGoodsStore-web/mysql_history
            MYSQL_PWD: db
            NODE_EXTRA_CA_CERTS: /mnt/ddev-global-cache/mkcert/rootCA.pem
            PGDATABASE: db
            PGHOST: db
            PGPASSWORD: db
            PGUSER: db
            PHP_IDE_CONFIG: serverName=TnVGoodsStore.ddev.site
            SSH_AUTH_SOCK: /home/.ssh-agent/socket
            TZ: ""
            USER: dinht
            VIRTUAL_HOST: tnvgoodsstore.ddev.site
            npm_config_cache: /mnt/ddev-global-cache/npm
        external_links:
            - ddev-router:tnvgoodsstore.ddev.site
        healthcheck:
            interval: 1s
            retries: 70
            start_interval: 1s
            start_period: 4m0s
            timeout: 1m10s
        hostname: TnVGoodsStore-web
        image: ./.ddev/.webimageBuild-TnVGoodsStore-built
        labels:
            com.ddev.app-type: drupal8
            com.ddev.approot: D:\StudyHK1_2024\mystore
            com.ddev.platform: ddev
            com.ddev.site-name: TnVGoodsStore
        networks:
            ddev_default: null
            default: null
        ports:
            - host_ip: 127.0.0.1
              mode: ingress
              protocol: tcp
              target: 80
            - host_ip: 127.0.0.1
              mode: ingress
              protocol: tcp
              target: 443
        restart: "no"
        user: 1000:1000
        volumes:
            - source: project_mutagen
              target: /var/www
              type: volume
              volume:
                nocopy: true
            - source: project_mutagen
              target: /tmp/project_mutagen
              type: volume
              volume:
                nocopy: true
            - bind:
                create_host_path: true
              read_only: true
              source: /d/StudyHK1_2024/mystore/.ddev
              target: /mnt/ddev_config
              type: bind
            - bind:
                create_host_path: true
              read_only: true
              source: /d/StudyHK1_2024/mystore/.ddev/xhprof
              target: /usr/local/bin/xhprof
              type: bind
            - bind:
                create_host_path: true
              source: /d/StudyHK1_2024/mystore/web/sites/default/files
              target: /var/www/html/web/sites/default/files
              type: bind
            - bind:
                create_host_path: true
              source: /d/StudyHK1_2024/mystore/.git
              target: /var/www/html/.git
              type: bind
            - source: ddev-global-cache
              target: /mnt/ddev-global-cache
              type: volume
              volume: {}
            - source: ddev-ssh-agent_socket_dir
              target: /home/.ssh-agent
              type: volume
              volume: {}
        working_dir: /var/www/html/
volumes:
    database:
        external: true
        name: TnVGoodsStore-mariadb
    ddev-global-cache:
        external: true
        name: ddev-global-cache
    ddev-ssh-agent_socket_dir:
        external: true
        name: ddev-ssh-agent_socket_dir
    project_mutagen:
        external: true
        name: TnVGoodsStore_project_mutagen
